version: '3.8'
services:
  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - "5000:5000"

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "3000:80"
